# 敏感词检测模型训练配置
# 直接编辑此文件即可修改训练参数

# 模型配置
model:
  name: "xlm-roberta-base"
  max_length: 512
  num_labels: 2

# 训练参数 - 防过拟合优化版本
training:
  # 基础参数
  batch_size: 8                    # 批次大小
  learning_rate: 1e-5              # 学习率
  num_epochs: 3                    # 训练轮数
  
  # 防过拟合参数
  weight_decay: 0.1                # 权重衰减 (L2正则化)
  max_grad_norm: 1.0               # 梯度裁剪
  label_smoothing_factor: 0.1      # 标签平滑
  
  # 早停配置
  early_stopping_patience: 2       # 早停耐心值
  early_stopping_threshold: 0.0005 # 早停阈值
  
  # 学习率调度
  warmup_steps: 100                # 预热步数
  warmup_ratio: 0.1                # 预热比例
  lr_scheduler_type: "cosine_with_restarts"  # 学习率调度器
  
  # 梯度和内存优化
  gradient_accumulation_steps: 2   # 梯度累积步数
  gradient_checkpointing: true     # 梯度检查点
  
  # 评估和保存
  eval_strategy: "steps"           # 评估策略
  eval_steps: 50                   # 评估间隔
  save_strategy: "steps"           # 保存策略
  save_steps: 100                  # 保存间隔
  logging_steps: 25                # 日志间隔
  
  # 模型选择
  load_best_model_at_end: true     # 加载最佳模型
  metric_for_best_model: "eval_loss"  # 最佳模型指标
  greater_is_better: false         # 损失越小越好
  
  # 数据加载优化
  dataloader_pin_memory: true      # 固定内存
  dataloader_drop_last: true       # 丢弃最后批次
  remove_unused_columns: true      # 移除未使用列
  
  # 随机种子
  seed: 42                         # 随机种子

# 数据配置
data:
  train_ratio: 0.7                 # 训练集比例
  val_ratio: 0.1                   # 验证集比例
  test_ratio: 0.2                  # 测试集比例
  random_seed: 42                  # 数据分割随机种子

# 快速配置预设 (注释掉不使用的)
presets:
  # 取消注释以使用预设配置
  
  # conservative:  # 保守训练 (防过拟合)
  #   learning_rate: 5e-6
  #   batch_size: 6
  #   weight_decay: 0.15
  #   early_stopping_patience: 1
  #   label_smoothing_factor: 0.15
  
  # fast:  # 快速训练
  #   learning_rate: 2e-5
  #   batch_size: 12
  #   num_epochs: 2
  #   early_stopping_patience: 3
  #   eval_steps: 100
  
  # high_quality:  # 高质量训练
  #   learning_rate: 8e-6
  #   batch_size: 4
  #   num_epochs: 5
  #   weight_decay: 0.12
  #   early_stopping_patience: 3
  #   eval_steps: 25
